name: linear_blur_venv
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - pip=22.2.2
  - pytorch-cuda
  - pytorch
  - torchvision
  - torchmetrics
  - pip:
    - tqdm>=4.64.1
    - clean-fid==0.1.35
    - lightning-utilities==0.5.0
    - matplotlib==3.6.2
    - numpy==1.24.1
    - pandas==1.5.2
    - pillow==9.3.0
    - pytorch-lightning==1.8.6
    - tensorboard==2.11.0
